---
title: "oldFLEXDASHBOARD_CODe"
output: html_document
date: '2023-02-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

USNVC_full <- Reduce(function (...) { merge(..., all = TRUE) },  # Full join
                           list(USNVC_common, 
                                sapling_barplot,
                                seedling_barplot,
                                tree_basics_barplot))

USNVC_fulltest <- USNVC_full %>%
  dplyr::select(Community_1,
         Parent_1, 
         Common_Name,
         Translated_Name,
         TotalSeedCount,
         TotalSapCount,
         TotalTreeCount) %>%
  dplyr::group_by(Community_1,
           Parent_1, 
           Translated_Name, 
           Common_Name) %>%
  dplyr::summarise(across(TotalSeedCount:TotalTreeCount, sum, na.rm = TRUE), .groups = 'drop')
```


```{r, eval = FALSE}
USNVC_fulltestA <- USNVC_fulltest %>%
  dplyr::filter(Parent_1 == "Appalachian & Interior Mesophytic Forest") %>%
  tidyr::pivot_longer(
               cols = starts_with("Total"),
               names_to = "Tree_Type", 
               values_to = "Count") 

USNVC_fulltestA <- USNVC_fulltestA %>%
  dplyr::group_by(Tree_Type) %>%
  dplyr::mutate(Prop = (Count/(sum(Count)) * 100))

```

```{r, eval = FALSE}

plot_stackedbarA <- USNVC_fulltestA %>% 
  ggplot(aes(y = Prop,
             x = Tree_Type, 
             fill = Common_Name)) + 
  geom_bar(position = "fill",stat = "identity", width = 0.25) +
  theme_clean() +
  xlab("")+ 
  ylab("") +
  theme(legend.position = "bottom", 
        legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Greens") + 
  guides(fill=guide_legend(ncol=2))

```

``` {r, eval = FALSE}
USNVC_fulltestB <- USNVC_fulltest %>%
  dplyr::filter(Parent_1 == "South-Central Interior Oak Forest") %>%
  tidyr::pivot_longer(
               cols = starts_with("Total"),
               names_to = "Tree_Type", 
               values_to = "Count") 

USNVC_fulltestB <- USNVC_fulltestB %>%
  dplyr::group_by(Tree_Type) %>%
  dplyr::mutate(Prop = (Count/(sum(Count)) * 100))

```

```{r, eval = FALSE}

plot_stackedbarB <- USNVC_fulltestB %>% 
  ggplot(aes(y = Prop,
             x = Tree_Type, 
             fill = Common_Name)) + 
  geom_bar(position = "fill",stat = "identity", width = 0.25) +
  theme_clean() +
  xlab("")+ 
  ylab("") +
  theme(legend.position = "bottom", 
        legend.title = element_blank()) + 
  scale_fill_brewer(palette = "Greens") + 
  guides(fill=guide_legend(ncol=2))
```

```{r}
USNVC_fulltest <- USNVC_fulltest %>%
  dplyr::mutate(Community_1 = as.factor(Community_1), 
                Parent_1 = as.factor(Parent_1), 
                Translated_Name = as.factor(Translated_Name), 
                Common_Name = as.factor(Common_Name), 
                TotalSeedCount = as.integer(TotalSeedCount), 
                TotalSapCount = as.integer(TotalTreeCount))

Categorical.Variables = c("Community_1", "Parent_1")
Numeric.Variables = c("TotalTreeCount", "TotalSeedCount", "TotalSapCount")
```

